version: '3.9'

services:
    php:
        build: ./image/php/
        container_name: php
        restart: unless-stopped
        volumes:
            - .:/var/www/html

    nginx:
        image: nginx:latest
        container_name: nginx
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html
            - ./image/nginx/default.conf:/etc/nginx/conf.d/default.conf

        links:
            - php
